// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{
    HELLO_GUEST_ELF, HELLO_GUEST_ID, HELLO_GUEST_PATH
};
use risc0_zkvm::{default_prover, sha::Digestible, ExecutorEnv, ProverOpts, VerifierContext};
use risc0_ethereum_contracts::{alloy::hex::ToHexExt, encode_seal};
use std::{env, io::Read};


fn u32_array_to_hex_string(arr: &[u32]) -> String {
    arr.iter()
        .map(|&num| format!("{:08x}", num.to_be())) // Format each u32 as 8-digit hex
        .collect::<Vec<String>>() // Collect into a vector of strings
        .join("") // Join them into a single string
}

fn main() {

    let args: Vec<String> = env::args().collect();
    let pk_hex = args[1].clone();
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // An executor environment describes the configurations for the zkVM
    // including program inputs.
    // An default ExecutorEnv can be created like so:
    // `let env = ExecutorEnv::builder().build().unwrap();`
    // However, this `env` does not have any inputs.
    //
    // To add guest input to the executor environment, use
    // ExecutorEnvBuilder::write().
    // To access this method, you'll need to use ExecutorEnv::builder(), which
    // creates an ExecutorEnvBuilder. When you're done adding input, call
    // ExecutorEnvBuilder::build().

    let exec_env = ExecutorEnv::builder()
        .write(&pk_hex)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest


    println!("workspace: {:?}", std::env::current_dir().unwrap());
    println!("GUEST_ADDR: {}", HELLO_GUEST_PATH);
    println!("GUEST_ELF length: {}", HELLO_GUEST_ELF.len());
    println!("GUEST_ELF_ID length: {}", HELLO_GUEST_ID.len());
    let prove_info = prover
        .prove_with_ctx(
            exec_env,
            &VerifierContext::default(),
            HELLO_GUEST_ELF,
            &ProverOpts::groth16()
        )
        .unwrap();

    // extract the receipt.
    let receipt = prove_info.receipt;

    // For example:
    //let output: u32 = receipt.journal.decode().unwrap_or_else(|error| {
    //    eprintln!("Failed to open the file: {}", error);
    //    std::process::exit(1); // Gracefully exit the program
    //});

    let encoded = encode_seal(&receipt).unwrap().encode_hex();
    let journal = receipt.journal.bytes.clone();

    // Decode Journal: Upon receiving the proof, the application decodes the journal to extract
    // the verified number. This ensures that the number being submitted to the blockchain matches
    // the number that was verified off-chain.
    //let y = U256::from(output);
    //let journal_digest = U256::abi_encode(&y);

    println!("journal digest as is: 0x{}", journal.digest());


    //let hash = Sha256::digest(&journal_digest);

    println!("encoded seal: 0x{}", encoded);
    println!("elf id: 0x{}", u32_array_to_hex_string(&HELLO_GUEST_ID));

    //receipt
    //    .verify(HELLO_GUEST_ID)
    //    .unwrap();

    println!("I generated a proof of execution! {} is a public output from journal ", encoded);
}
