[package]
name = "hzys_produce_attestation"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
slog = { version = "2", features = ["max_level_debug", "release_max_level_debug", "nested-values"] }
# account_utils = { path = "../common/account_utils" }
serde = { version = "1", features = ["derive"] }
fixed_bytes = { path = "../consensus/fixed_bytes" }
safe_arith = { path = "../consensus/safe_arith" }

