[package]
name = "hzystest"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
methods = { path = "../methods" }
tokio = { workspace = true }
serde = "1.0"
serde_json = "1.0"
safe_arith = { path = "../consensus/safe_arith" }
borsh = "1.0"
alloy-chains = {version = "0.2.0"}
alloy = { workspace = true }
alloy-primitives = { workspace = true }
url = { workspace = true }
state_processing = { workspace = true }
beacon_chain = { workspace = true }
bls = { workspace = true }
types = { workspace = true }
hzys_produce_attestation = {path ="../hzys_produce_attestation"}
